---
- name: 'Configure PAM and PolKit'
  hosts: pam
  become: true
  tasks:

    - name: 'Add Docker repository'
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644

    - name: 'Configure Docker Edge repo'
      ini_file:
        dest: '/etc/yum.repos.d/docker-ce.repo'
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: 'Configure Docker Test repo'
      ini_file:
        dest: '/etc/yum.repos.d/docker-ce.repo'
        section: 'docker-ce-test'
        option: enabled
        value: 0

    - name: 'Install containerd'
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm
        state: present

    - name: 'Install Docker'
      yum:
        name: docker-ce
        state: present

    - name: 'Install Docker cli'
      yum:
        name: docker-ce-cli
        state: present

    - name: 'Start Docker service'
      service:
        name: docker
        state: started
        enabled: yes

    - name: 'Create admin group'
      group:
        name: 'admin'
        state: present

    - name: 'Create users'
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"

    - name: 'Allow password authentication via ssh'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*$'
        line: 'PasswordAuthentication yes'
      notify:
        - restart sshd

    - name: 'Copy restricting script'
      copy:
        src: ../sources/restrict_login.sh
        dest: /usr/local/bin/restrict_login.sh
        mode: a+x

    - name: 'Copy PolKit rules'
      copy: src='{{ item }}' dest='/etc/polkit-1/rules.d/'
      with_items:
        - ../sources/00-access.rules
        - ../sources/01-dockerrestart.rules

    - name: 'Edit /etc/pam.d/sshd'
      lineinfile:
        dest: /etc/pam.d/sshd
        line: 'account    required	pam_exec.so /usr/local/bin/restrict_login.sh'
        insertafter: 'account    required     pam_nologin.so'

    - name: 'Edit /etc/pam.d/login'
      lineinfile:
        dest: /etc/pam.d/login
        line: 'account    required	pam_exec.so /usr/local/bin/restrict_login.sh'
        insertafter: 'account    required     pam_nologin.so'
  
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted