---
- hosts: all
  become: true
  roles:
    - initial_configure

- hosts: master
  become: true
  roles:
    - master

- hosts: slave
  become: true
  roles:
    - slave

- hosts: barman
  become: true
  roles:
    - barman
