---
- name: 'Deploy zabbix agent'
  hosts: agent
  become: true
  tasks:
    
    - name: 'Install zabbix configuration package from rpm'
      yum:
        name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
        state: present
        
    - name: 'Install zabbix agent'
      yum:
        name: zabbix-agent
        state: present

    - name: 'Copy config fot zabbix agent'
      copy:
        src: ../configfiles/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf

    - name: 'Set timezone'
      timezone:
        name: Europe/Moscow

    - name: 'Start zabbix agent service'
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes