# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.10.10"
    master.vm.hostname = "master"
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.10.20"
    slave.vm.hostname = "slave"
  end

  config.vm.define "barman" do |barman|
    barman.vm.network "private_network", ip: "192.168.10.30"
    barman.vm.hostname = "barman"
  end

  config.vm.provision "pgqsl", type:'ansible' do |ansible|
    ansible.inventory_path = './inventories/all.yml'
    ansible.playbook = './pgsql.yml'
  end
end